### ISSUE TITLE
Some error when I run distribution_representation.py

### ISSUE THREAD

**Issue by xjsxjs** [fnzhan/Illumination-Estimation#17]
Traceback (most recent call last):
  File "distribution_representation.py", line 145, in <module>
    para, map = extractor.compute(hdr)
  File "distribution_representation.py", line 94, in compute
    hdr = self.steradian * hdr
ValueError: operands could not be broadcast together with shapes (128,256,1) (1024,2048,3) 

When I run distribution_representation.py, I encounter the above error, how can I solve it, thank you！

**Comment by fnzhan** [comment]
It seems to be caused by the image size, you may check it. The default size of panorama in my work is 256 * 128.

**Comment by xjsxjs** [comment]
> It seems to be caused by the image size, you may check it. The default size of panorama in my work is 256 * 128.

Hello sir, thank you for your reply, maybe there are some problems with my understanding, I thought distribution_representation.py can be run directly with the original Laval data set, do you need other data preprocessing, can you share how it is processed, Thanks again!

**Comment by fnzhan** [comment]
> 

Yes, it requires some preprocessing as described in "deep parametric indoor lighting estimation". I directly got the preprocessed data by contacting the author.

**Comment by xjsxjs** [comment]
> > 
> 
> Yes, it requires some preprocessing as described in "deep parametric indoor lighting estimation". I directly got the preprocessed data by contacting the author.

Thank you for your reply!

**Comment by half-orange-v** [comment]
Excuse me, have you got the dataset? I sent an email to the author, but he didn't reply.
