### ISSUE TITLE
evaluation metrix

### ISSUE THREAD

**Issue by ad45675** [fnzhan/Illumination-Estimation#20]
HI~I have some question about REMS and si-REMS.
I know the matrix, but i don't know which parameter will be calculated.
is the illumination map?
I also want to ask  that how to calculate the Angular Error.

 thanks!

**Comment by fnzhan** [comment]
Hi, they are computed on the images rendered with illumination maps.
For angular error, please refer to DeepLight: Learning Illumination for Unconstrained Mobile Mixed Reality

**Comment by ad45675** [comment]
hi @fnzhan ,

when i run the training code , i got some error,

```
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    dist_emloss = Sam_Loss(dist_pred, dist_gt).sum() * 1000.0
  File "/venv/py37_zero-XRWy4lKA/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'geometry'
```
so you have use the geometry in the training?
